# -*- coding: utf-8 -*-
"""stop_line_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f2mfkXy_-2PbnKF_GwsBaQjmClirxbi6
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

model = YOLO('yolov8n.pt')
model.predict(
   source='/content/frame0.jpg',
   conf=0.25
)

# Load a model
model = YOLO('yolov8n.yaml')  # build a new model from scratch

# Use the model
results = model.train(data='/content/data.yaml', epochs=15)  # train the model
results = model.val()  # evaluate model performance on the validation set
results = model('/content/frame0.jpg')  # predict on an image
success = model.export(format='onnx')  # export the model to ONNX format